
menu.nombre.principal=Principal
menu.nombre.estilo=Cambiar Estilo
menu.nombre.idioma=Idioma
menu.nombre.producto=Producto
menu.nombre.venta=Venta

menuitem.nombre.salir=Salir
menuitem.nombre.producto=Administrar Producto
menuitem.nombre.venta=Reg.Venta
menuitem.nombre.venta2=Reg.Cliente
