
menu.nombre.principal=Accueil
menu.nombre.estilo=Changer de style
menu.nombre.idioma=Langue
menu.nombre.producto=Produit
menu.nombre.venta=Vente

menuitem.nombre.salir=Quitter
menuitem.nombre.producto=Gérer le produit
menuitem.nombre.venta=Enregistrer la vente
menuitem.nombre.venta2=Enregistrer le client